{
	"version": 1540441065,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/justbreathebg-sheet0.png",
		"images/mainmenubg-sheet0.png",
		"images/rainydaybg-sheet0.png",
		"images/grass-sheet0.png",
		"images/skystate-sheet0.png",
		"images/rainoverlay-sheet0.png",
		"images/rainoverlay-sheet1.png",
		"images/rainoverlay-sheet2.png",
		"images/arainydaybutton-sheet0.png",
		"images/aboutbutton-sheet0.png",
		"images/breathinginstructions-sheet0.png",
		"images/calmmindtitle-sheet0.png",
		"images/getbutton-sheet0.png",
		"images/justbreathebutton-sheet0.png",
		"images/instructions-sheet0.png",
		"images/mainmenubutton-sheet0.png",
		"images/aboutscreentext-sheet0.png",
		"images/mainmenubuttonblack-sheet0.png",
		"images/helplines-sheet0.png",
		"images/breathingcircle-sheet0.png",
		"images/character-sheet0.png",
		"images/character-sheet1.png",
		"images/sun-sheet0.png",
		"images/touchcircle-sheet0.png",
		"images/umbrella-sheet0.png",
		"media/just breathe 3.ogg",
		"media/a rainy day.ogg",
		"media/rain_on_roof.m4a",
		"media/rain_on_roof.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}